name: Test Unit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  # Install packages into system environment.
  # Follows: https://docs.astral.sh/uv/guides/integration/github/#using-uv-pip
  UV_SYSTEM_PYTHON: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-code-changes:
    name: Detect Code Changes
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.filter.outputs.run-tests }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          list-files: shell
          filters: |
            run-tests:
              - '!docs/**'
              - '!docker/**'
              - '!.github/**'
              - '.github/workflows/test_unit.yml'
  test-unit:
    name: Test Unit
    needs: detect-code-changes
    if: needs.detect-code-changes.outputs.run-tests == 'true'
    strategy:
      matrix:
        runners: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set Up uv
        uses: astral-sh/setup-uv@v7
        id: setup-uv
        with:
          version: 0.11.15
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Set Up Environment
        run: |
          make install-pinned-3.13
      - name: Run Pytest
        run: |
          make test-ci-maximal
